parameters:
    kiboko.entity.slider.class: SliderBundle\Entity\Slider
    kiboko.entity.slide.class: SliderBundle\Entity\Slide

services:
    kiboko.form.autocomplete.slider.search_handler:
        public: false
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%kiboko.entity.slider.class%'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: kiboko_slider }

    kiboko.repository.slider:
        class: 'SliderBundle\Entity\Repository\SliderRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - '%kiboko.entity.slider.class%'


    kiboko.data_provider.slider:
        class: 'SliderBundle\Layout\DataProvider\SliderDataProvider'
        arguments:
            - '@kiboko.repository.slider'
            - '@oro_config.manager'
            - "@oro_scope.scope_manager"
            - "@kiboko.slide.resolver"
        tags:
            - { name: layout.data_provider, alias: slider }

    kiboko.slide.resolver:
        class: 'SliderBundle\Slide\SlideResolver'
        arguments:
            - "@property_accessor"


    kiboko.slider.customer_scope_criteria_provider.link:
        public: false
        tags:
            - { name: oro_service_link, service: oro_customer.customer_scope_criteria_provider }
            - { name: oro_scope.provider, scopeType: slide, priority: 30 }

    kiboko.slider.customer_group_scope_criteria_provider.link:
        public: false
        tags:
            - { name: oro_service_link, service: oro_customer.customer_group_scope_criteria_provider }
            - { name: oro_scope.provider, scopeType: slide, priority: 30 }

    kiboko.slider.website_scope_criteria_provider:
        tags:
            - { name: oro_service_link, service: oro_website.website_scope_criteria_provider }
            - {name: oro_scope.provider, scopeType: slide, priority: 30}

    kiboko.slider.localization_criteria_provider:
        tags:
            - { name: oro_service_link, service: oro_cms.localization_scope_criteria_provider }
            - { name: oro_scope.provider, scopeType: slide, priority: 30}
